### ISSUE TITLE
Python error with latest version

### ISSUE THREAD

**Issue by cirdanmiriel** [crazy-max/docker-firefox-syncserver#55]
#### Steps to reproduce this issue

1. Updated from v1.8.0 to latest

#### Expected behaviour

> Everythin should be running

#### Actual behaviour

> My container is crashlooping with these logs:

```
Setting timezone to Europe/Paris...
Checking prerequisites...
Generating configuration...
Fixing perms...
[2022-03-21 16:21:40 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2022-03-21 16:21:40 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2022-03-21 16:21:40 +0000] [1] [INFO] Using worker: sync
[2022-03-21 16:21:40 +0000] [14] [INFO] Booting worker with pid: 14
[2022-03-21 16:21:41 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 69, in load_pasteapp
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/app/syncserver/__init__.py", line 265, in main
    config = get_configurator(global_config, **settings)
  File "/app/syncserver/__init__.py", line 257, in get_configurator
    config.include(includeme)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    c(configurator)
  File "/app/syncserver/__init__.py", line 149, in includeme
    config.include("syncstorage", route_prefix="/storage")
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    c(configurator)
  File "/usr/local/lib/python2.7/site-packages/syncstorage/__init__.py", line 18, in includeme
    config.include("syncstorage.storage")
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    c(configurator)
  File "/usr/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 561, in includeme
    storage = load_storage_from_settings("storage", settings)
  File "/usr/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 585, in load_storage_from_settings
    return klass(**section_settings)
  File "/usr/local/lib/python2.7/site-packages/syncstorage/storage/sql/__init__.py", line 130, in __init__
    self.dbconnector = DBConnector(sqluri, **dbkwds)
  File "/usr/local/lib/python2.7/site-packages/syncstorage/storage/sql/dbconnect.py", line 357, in __init__
    self.engine = create_engine(sqluri, **sqlkw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 632, in dbapi
    import psycopg2
ImportError: No module named psycopg2
[2022-03-21 16:21:41 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-03-21 16:21:41 +0000] [1] [INFO] Shutting down: Master
[2022-03-21 16:21:41 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by mind-overflow** [comment]
Same issue. I had to roll back to a previous version because the container would just fail to start.
